name: CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    # Validate changelog
    validate-changelog:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Get changelog entry
              # uses: mindsers/changelog-reader-action@v2
              # uses: coditory/changelog-parser@v1
              # uses: kiyoon/parse-changelog-action@v1
              # uses: alleyinteractive/action-changelog-extractor@v0.1.0
              run: tools\ExtractChangelog.ps1 -tag v1.5.0 -changelogPath CHANGELOG.md -extractedChangelogPath artifacts\CHANGELOG-extract.md
